### ISSUE TITLE
Error in extraction with a group of "|" separated keywords.

### ISSUE THREAD

**Issue by miguelfc** [miguelfc/marble#26]
core_1                 | twitter4j.TwitterException: 403:The request is understood, but it has been refused. An accompanying error message will explain why. This code is used when requests are being denied due to update limits (https://support.twitter.com/articles/15364-about-twitter-limits-update-api-dm-and-following).
core_1                 | message - Missing or invalid url parameter.
core_1                 | code - 195
core_1                 |
core_1                 |        at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:164)
core_1                 |        at twitter4j.HttpClientBase.request(HttpClientBase.java:57)
core_1                 |        at twitter4j.HttpClientBase.get(HttpClientBase.java:75)
core_1                 |        at twitter4j.TwitterImpl.get(TwitterImpl.java:1786)
core_1                 |        at twitter4j.TwitterImpl.search(TwitterImpl.java:268)
core_1                 |        at org.marble.commons.service.TwitterSearchServiceImpl.search(TwitterSearchServiceImpl.java:112)
core_1                 |        at org.marble.commons.executor.extractor.TwitterExtractionExecutor.run(TwitterExtractionExecutor.java:141)
core_1                 |        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
core_1                 |        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
core_1                 |        at java.lang.Thread.run(Thread.java:745)

**Comment by miguelfc** [comment]
This happens with searches with a lot of keywords. It seems not to be related to the length of the query (at least in our case), but with the number of words in it (with 95 word works, with 96 throws an error). But as it is not documented, marble needs to handle this.
